name: Notify Telegram on Merge to Main/Master

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot7467670477:AAGM3G17smven1d2-aPZGA_y6-ZwPzYQcpo/sendMessage" \
            -d chat_id=1198472331 \
            -d text="kasian adzka di ghosting"